#ifndef TOKEN_H
#define TOKEN_H

#include <string>

enum class TokenType
{
    NUMBER, STRING, IDENTIFIER, IDENTIFICATION, ENVIRONMENT, DATA, PROCEDURE,
    DIVISION, SECTION, PROGRAM_ID, AUTHOR, DATE_WRITTEN, PIC, IS, VALUE, COMP,
    DISPLAY, STOP, RUN, MOVE, TO, ADD, GIVING, SUBTRACT, MULTIPLY, DIVIDE,
    COMPUTE, IF, ELSE, END_IF, START, THEN, PERFORM, END_PERFORM, UNTIL, TIMES,
    VARYING, FROM, BY, INTO, GO, NOT, AND, OR, EQUAL, GREATER, LESS, THAN, THRU,
    INPUT_OUTPUT, FILE_CONTROL, SELECT, ASSIGN, FD, SD, RECORD, INDEXED, DYNAMIC,
    LABEL, STANDARD, OMITTED, WORKING_STORAGE, LOCAL_STORAGE, LINKAGE, FILE_SECTION,
    INSPECT, REPLACING, ALL, ZEROS, SPACES, OPEN, CLOSE, READ, WRITE, INPUT, OUTPUT,
    EXTEND, I_O, AT, END, ORGANIZATION, LINE, SEQUENTIAL, ACCESS, MODE, RECORDS, STATUS,
     NEXT, KEY, END_START, END_READ, END_WRITE, DOT, COMMA, LPAREN, RPAREN, PLUS, MINUS, MUL, DIV_OP,
    DOLLAR, EQUALS, GREATER_THAN, LESS_THAN, NEWLINE, EOF_TOKEN, INVALID,
    RELATIVE, RANDOM, KEYED, ALTERNATE, WITH, DUPLICATES, MANUAL, AUTOMATIC, LOCK,
     PRINT, OCCURS, TABLE, SEARCH, SET, ASCENDING, DESCENDING,
     END_SEARCH, UP, DOWN,
     REMAINDER, ACCEPT,
     JUST, LEFT, RIGHT, REDEFINES,
     EVALUATE, END_EVALUATE, WHEN, OTHER, TRUE,
     STRING_OP, END_STRING_OP, UNSTRING, END_UNSTRING,
      POINTER, DELIMITED, SIZE, OVERFLOW, TALLYING, IN, ON
 };

struct Token
{
    TokenType type;
    std::string lexeme;
    int line;
    int column;
};

#endif
